services:
  # The "Storage" Layer
  flights_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}      # Defaults to 'admin' if not in .env
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_flight_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # The "Ingestion" Layer
  sky_ingestor:
    build: ./ingestor
    depends_on:
      flights_db:
        condition: service_healthy # Only starts once DB passes healthcheck
    environment:
      DB_HOST: flights_db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

volumes:
  pg_flight_data: