services:
  # The "Storage" Layer
  flights_db:
    image: postgres:15
    environment:
      POSTGRES_USER: "root"       # Defaults to 'admin' if not in .env
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "flights_data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d flights_data"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_flight_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # The "Ingestion" Layer
  sky_ingestor:
    build: ./ingestor
    depends_on:
      flights_db:
        condition: service_healthy # Only starts once DB passes healthcheck
    environment:
      DB_HOST: flights_db

volumes:
  pg_flight_data: